# Generated by Django 4.1 on 2022-08-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0002_phone_no_delete_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option1_count',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2_count',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3_count',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4_count',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.DeleteModel(
            name='choice',
        ),
    ]
